services:
  frontend:
    build:
      context: ./files
      dockerfile: front.Dockerfile 
    ports:
      - "80:80"
    volumes:
      - ./code:/code
    networks:
      - internal-docker

  backend:
    build:
      context: ./files
      dockerfile: back.Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - "networkvolume:/Windows/backups"
    networks:
      - internal-docker

  php:
    build:
      context: ./files
      dockerfile: php.Dockerfile
    volumes:
      - ./code:/code
    networks:
      - internal-docker

  db-viewer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - internal-docker

volumes:
  networkvolume:
    driver_opts:
      type: cifs
      o: "user=B.Vandenbus@intec-cloud.com,password=intec-123"
      device: "//172.16.42.4/Docker-Backups$$"

networks:
  internal-docker: {}
